version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.11.0-management
    container_name: rabbimq
    hostname: line
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: name 
      POSTGRES_USER: username 
      POSTGRES_PASSWORD: password 
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
  telegram:
    restart: unless-stopped
    build:
      .
    command:
      python3 main.py
    depends_on:
      - db
    networks:
      - default
